apiVersion: v1
kind: Pod
metadata:
  name: openebs-test
  label:
    apps: openebs-test
spec:
  restartPolicy: Never
  containers:
  - name: perfrunner
    image: k8s.gcr.io/e2e-test-images/jessie-dnsutils:1.3
    command: ["/bin/bash"]
    args: ["-c", "while true ;do sleep 50; done"]
    volumeMounts:
       - mountPath: /datadir
         name: openebs-test-blockdevice
    tty: true
  volumes:
  - name: openebs-test-blockdevice
    persistentVolumeClaim:
      claimName: 